batch_size: 256
test_batch_size: 100
lr: 0.1
momentum: 0.9
decay: 0.0005
epochs: 1
save_on_epochs: []
optimizer: SGD
log_interval: 100


scheduler: False


data: multimnist

poisoning_proportion: .5
poison_number: 8
backdoor: False
alpha: 0.95
scale_threshold: 0.1

normalize: eq

save_model: False
log: False
tb: False

random: False
gan: False
defense: True
transform_train: True

nc: False
smoothing: False

losses:
  - backdoor
  - normal
  - sums
#  - nc_adv
#  - ewc
#  - latent
#  - latent_fixed

losses_scales:
  backdoor: 0.33
  normal: 0.22
  sums: 0.43